---
title: "Problem Set #4"
author: "Beau Meche"
date: "02-25-2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(gt)
library(devtools)
library(lubridate)
```

#Question 1
```{r echo = FALSE, message=FALSE}
poll <- read_csv(file = "ps_4_elections-poll-nc09-3.csv")

#Question 1
W <- poll %>%
  group_by(response) %>%
  count() %>%
  spread(response, n)

# ML #1: dem voters
dems <- W %>%
  pull(Dem)

#ML #2: republicans more than undecideds
ML2 <- W %>%
  mutate(r_u = Rep - Und) %>%
  pull(r_u)

#ML #3: number of gender that didnt match gender combined
ML3 <- poll %>%
  filter(gender != gender_combined) %>%
  count() %>% pull (n)

#ML #4: race column discrepancies
ML4 <- poll %>%
  select(race_eth, file_race_black) %>%
  filter(race_eth == "White" &
         file_race_black != "White") %>%
  count() %>% pull(n)

#ML #5: fastest Rep vs. fastest Dem
ML5 <- poll %>%
  filter(response == "Dem" | response == "Rep") %>%
  group_by(response) %>%
  summarize(time = min(timestamp)) %>%
  spread(response, time) %>%
  mutate(diff = round(Rep - Dem, 0)) %>%
  select(diff)
```
## add the sentences here

#Question 2
```{r echo=FALSE, message=FALSE}
chart <- poll %>%
  select(response, race_eth, final_weight) %>%
  filter(race_eth != "[DO NOT READ] Don't know/Refused") %>%
  mutate(race_eth = fct_relevel(race_eth, c("White", "Black", "Hispanic", "Asian", "Other")))%>%
  group_by(race_eth, response) %>%
  summarize(total = sum(final_weight)) %>%
  spread(key = response, value = total, fill = 0) %>%
  ungroup()

chart %>%
  mutate(all = Dem+Rep+Und+`3`)%>%
  mutate(Dem = Dem/all) %>%
  mutate(Rep = Rep/all) %>%
  mutate(Und = Und/all) %>%
  select(-all, -`3`) %>%
  ungroup() %>%
  na_if(0) %>%
  gt() %>%
fmt_percent(columns = vars(Dem, Rep, Und), decimals = 0) %>%
    tab_header(
        title = ("Demographic Polling Results in N.C. 9")) %>%
    tab_source_note(source_note = "New York Times Upshot/Siena College 2018 live polls") %>%
    cols_label(
      race_eth = "",
      Dem = "DEM.",
      Rep = "REP.",
      Und = "UND.")
```


#Question 3

```{r echo=FALSE, message=FALSE}
ew <- poll %>%
select(educ, final_weight) %>%
  filter(educ != "[DO NOT READ] Refused") %>%
  mutate(educ = fct_relevel(educ, c("Grade school", "High school", 
                                    "Some college or trade school", "Bachelors' degree", "Graduate or Professional Degree"))) %>%
  ggplot(aes(x = educ, y = final_weight)) + geom_violin() + coord_flip() +    geom_jitter(alpha = .4, width = .22) + 
  labs(title ="More Educated Matter Less in North Carolina 9th",
       subtitle ="Poll gives more weight to people who are less likely to participate in polls",
       caption = "New York Times Upshot/Siena College 2018 live polls")+
  xlab(NULL) + 
  ylab("Weight Given to Respondent in Calculating Poll Results")
ew
```





